import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Newsletter from "@/components/Newsletter";
import About from "@/components/About";
import Hero from "@/components/Hero";
import Events from "@/components/Events";
import Disclaimer from "@/components/Disclaimer";
//import { ThemeProvider } from "@material-tailwind/react";
import { StyledEngineProvider } from "@mui/material";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/* <ThemeProvider> */}
      <body className={inter.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    {/* </ThemeProvider> */}
    </html>
    
  );
}
